"""
Main orchestrator - ties everything together.
Runs daily: scrape news -> generate post via Claude Code CLI -> approval UI -> post when approved.
Can also be triggered manually.

Pipeline:
  3 PM: Discovery — scrape news, build swipe cards (TF-IDF scored)
  5 PM: Generation — pick from liked articles, Claude Code CLI writes the post
"""
import asyncio
import sys
from datetime import datetime

from config import APPROVAL_URL
from news_scraper import gather_all_news
from post_generator import generate_post_draft, load_profile, pick_best_topic
from approval_server import run_server, send_reminder_notification
from linkedin_poster import post_approved_drafts
from news_discovery import discover_news


async def daily_pipeline(post_type: str = "news"):
    """Full daily pipeline: pick best article -> Claude generates -> approval -> post."""
    print("\n" + "=" * 60)
    print(f"  LINKEDIN AUTO-POSTER - {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"  Post type: {post_type}")
    print("=" * 60)

    print("\n[Step 1/3] Selecting best article...")
    profile = load_profile()
    best_article = pick_best_topic(profile=profile)

    if not best_article:
        print("  No discovery data available. Scraping fresh news...")
        articles = await gather_all_news()
        if not articles:
            print("  No articles found today. Skipping.")
            return
        best_article = pick_best_topic(articles=articles, profile=profile)

    if not best_article:
        print("  Could not find a suitable article. Skipping.")
        return

    print(f"  Selected: {best_article.get('title', 'Unknown')[:60]}")

    print("\n[Step 2/3] Generating post via Claude Code CLI...")
    draft = generate_post_draft(best_article, profile, post_type=post_type)

    print(f"  Draft created: {draft['id']}")
    print(f"  Generated by: {draft.get('generated_by', 'template')}")
    print(f"  Needs image: {draft.get('needs_image', False)}")

    print("\n[Step 3/3] Awaiting your approval...")
    print(f"  Open: {APPROVAL_URL}")
    send_reminder_notification()

    print("\n  Checking for previously approved posts...")
    await post_approved_drafts()

    print("\n" + "=" * 60)
    print("  Pipeline complete. Approve the new post at:")
    print(f"  {APPROVAL_URL}")
    print("=" * 60 + "\n")


def run_with_server():
    """Run the pipeline and keep the approval server running."""
    asyncio.run(daily_pipeline())
    print("\n[Server] Starting approval server...")
    run_server(open_browser=True)


async def discovery_pipeline():
    """3 PM discovery: scrape news and prepare swipe cards."""
    print("\n" + "=" * 60)
    print(f"  NEWS DISCOVERY - {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print("=" * 60)
    print("\n[Discovery] Fetching latest AI & tech news + research papers...")
    cards = await discover_news()
    print(f"\n[Discovery] {len(cards)} cards ready for review.")

    exploration_count = sum(1 for c in cards if c.get("is_exploration"))
    if exploration_count:
        print(f"  ({exploration_count} exploration cards mixed in)")

    research_count = sum(1 for c in cards if c.get("type") == "research")
    if research_count:
        print(f"  ({research_count} research papers included)")

    print(f"  Open the dashboard to swipe: {APPROVAL_URL}")

    try:
        from plyer import notification
        if cards:
            notification.notify(
                title="News Discovery Ready",
                message=f"{len(cards)} new articles to swipe through!",
                app_name="LinkedIn AutoPoster",
                timeout=10
            )
    except Exception:
        pass


async def generate_now(post_type: str = "news") -> dict | None:
    """On-demand post generation — triggered from the dashboard."""
    print(f"\n[Generate Now] Starting on-demand post generation (type={post_type})...")
    profile = load_profile()
    best_article = pick_best_topic(profile=profile)

    if not best_article:
        print("  No discovery data. Scraping fresh news...")
        articles = await gather_all_news()
        if not articles:
            return None
        best_article = pick_best_topic(articles=articles, profile=profile)

    if not best_article:
        return None

    draft = generate_post_draft(best_article, profile, post_type=post_type)
    print(f"[Generate Now] Draft created: {draft['id']}")
    return draft


def post_approved_only():
    """Just post any approved drafts without running the full pipeline."""
    asyncio.run(post_approved_drafts())


def run_discovery():
    """Run the discovery pipeline only."""
    asyncio.run(discovery_pipeline())


def scrape_only():
    """Just scrape news without generating or posting."""
    articles = asyncio.run(gather_all_news())
    print(f"\nFound {len(articles)} articles. Top 5:")
    for i, a in enumerate(articles[:5], 1):
        print(f"  {i}. [{a['type']}] {a['title'][:60]}")


def migrate_db():
    """Migrate existing JSON files to SQLite."""
    from database import migrate_from_json
    print("\n[Migration] Converting JSON files to SQLite...")
    migrate_from_json()
    print("[Migration] Done!")


def _arg(flag: str, default: str = None) -> str:
    """Pull --flag=value or default."""
    for a in sys.argv:
        if a.startswith(f"--{flag}="):
            return a.split("=", 1)[1]
    return default


if __name__ == "__main__":
    if "--help" in sys.argv or "-h" in sys.argv:
        print("""
LinkedIn Auto-Poster Scheduler
===============================
Usage:
  python scheduler.py                     Full pipeline + server (interactive)
  python scheduler.py --discover          Run 3 PM discovery pipeline
  python scheduler.py --generate          Generate a post now (default: news)
  python scheduler.py --generate --type=builder        Specific post type
  python scheduler.py --generate --type=audience_hook  Question hook for audience
  python scheduler.py --generate-via-claude        Same as --generate (5 PM cron entry)
  python scheduler.py --post              Only post approved drafts
  python scheduler.py --scrape            Only scrape news (no generation)
  python scheduler.py --server            Only start approval server
  python scheduler.py --migrate           Migrate JSON files to SQLite
  python scheduler.py --help              Show this help

Post types (--type=):
  news      News analysis with developer take (default)
  builder   Builder update from your work / commits
  hot_take  Short contrarian opinion
  research  Research paper / lab blog deep-read

The daily flow:
  3 PM: Discovery — scrapes AI news + research papers
        Swipe right (like) or left (skip) to train preferences
  5 PM: Generation — picks from today's liked articles,
        Claude Code CLI writes the post (uses your subscription, no API key)
  Approval — review, edit, approve or reject in the dashboard
  Posting — approved posts go to LinkedIn via Playwright
""")
    elif "--post" in sys.argv:
        post_approved_only()
    elif "--scrape" in sys.argv:
        scrape_only()
    elif "--discover" in sys.argv:
        run_discovery()
    elif "--generate" in sys.argv or "--generate-via-claude" in sys.argv:
        post_type = _arg("type", "news")
        asyncio.run(generate_now(post_type=post_type))
    elif "--server" in sys.argv:
        run_server(open_browser=True)
    elif "--migrate" in sys.argv:
        migrate_db()
    else:
        run_with_server()
